spring:
  application:
    name: ptw
    # 文件上传限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  port: 8080

# 文件上传配置
file:
  upload-dir: ./uploads/



# 日志配置
logging:
  level:
    root: INFO
    com.yufei.ptw: DEBUG

